name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Address https://github.com/keryell/music_utils/security/code-scanning/1
# "Workflow does not contain permissions #1"
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - run: pip install pytest
      - run: pytest tests/ -v
